language: python
sudo: false
services:
- xvfb
python:
- '2.7'
- '3.5'
- '3.6'
before_script:
- export DISPLAY=:99.0
- sleep 3
install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas
  scipy matplotlib seaborn scikit-learn
- source activate testenv
- pip install .[speech-decoding,efficient-learning]
script: py.test
notifications:
  slack:
    secure: aovihUl6ZPh96YPe83cQgxobxXK2xauqovtwlugv1A/J4zR8YZzbr4ykOOlJHnAOSrBUql1AU2+6QpbPx5dtYVvowI6VunaKUfsXMtQqKNNfQvcswOj9I6lLOi8ZUZt2ABZY6oEVFcawED21NeYSkrNmJndZ1n3j3b0XwxOkOFQtxrnVeRX6c/F6xPp5tu+f5ODDhitwq+IyCoKSu3WRBHvvtX8n0hJsRU2ZWI7G8mNDXkBybTjLG8wK+B5l9sPMa8y453+EbCDTgBDOMWSkKC7t6Cls+9qT48aRf3TEP0feI21bV/LbQN/GWPfz7paBHOUvadisWSJAEFmPuP1WlOL9noAU6OjHHl+87aqi2Cmw8ajcTbMhvCsmqascR3AIDfRBZFbq74duZ1yYiGlByUhPSLr2YkLbCL3WbYEgMvknvaAbKZkssXS70Xtyov1ynpD3uvGV4jVMFJntx672nz6VmJpyw4y6IZIV9Sh7zRaDZOKmE+iQQNEbH/2Bs5b0mW6QS8yH3Q5KML/RfD8P0FFScE4X6wZSQAjMvjIDtW3dlZkPurh7tyLHmkHNdlEcHzzRY/qXZo+qUUxDN2rKE0mI4fhaIbV4py9iNYsl4+G8WW1CkAf9YJPbfDQvSRugsN6nv7KH3JNv7Ne8kByO0s8qdCvl77POxv4vuQNAdkQ=
