import pytest
import quail
import os
import shutil

def test_decode_speech_smoke(tmp_path):
    # This test requires Whisper models which might be large.
    # We use 'tiny' model for speed if network available.
    
    # Check if 'test_audio.wav' exists (generated by command)
    # Ideally should generate here or use fixture.
    import numpy as np
    import scipy.io.wavfile as wav
    
    fname = tmp_path / "test_speech.wav"
    RATE=16000
    t=np.linspace(0, 1, RATE*1) # 1 second
    # Silence/Tone (Whisper might produce empty string or hallucinate)
    data=(np.sin(2*np.pi*440*t)*32767).astype(np.int16)
    wav.write(str(fname), RATE, data)
    
    try:
        # Run decode with tiny model
        res = quail.decode_speech(str(fname), model_size='tiny', fp16=False)
        # Result should be list of tuples or empty list
        assert isinstance(res, list)
        
        # We don't expect accurate transcription of a sine wave, 
        # but function should complete without error.
        
    except ImportError:
        pytest.skip("Whisper not installed")
    except Exception as e:
        # Network issues downloading model?
        pytest.fail(f"Decode failed: {e}")

def test_decode_speech_save(tmp_path):
    # Test saving functionality
    import numpy as np
    import scipy.io.wavfile as wav
    
    fname = tmp_path / "test_save.wav"
    RATE=16000
    data = np.zeros(RATE, dtype=np.int16) # Silence
    wav.write(str(fname), RATE, data)
    
    try:
        quail.decode_speech(str(fname), model_size='tiny', save=True, fp16=False)
        
        # Check files
        assert os.path.exists(str(fname) + ".p")
        assert os.path.exists(str(fname) + ".txt")
        
    except ImportError:
        pytest.skip("Whisper not installed")
    except Exception as e:
        pytest.fail(f"Decode save failed: {e}")
