import pytest
import quail
import pandas as pd
import numpy as np

def test_fingerprint_update():
    # Setup initial fingerprint as array to avoid DataFrame/Array shape mismatch issues
    # The default return from helper is array (np.mean(df, 0)).
    arr = np.array([0.5, 0.5])
    fp = quail.Fingerprint(state=arr, n=1)
    
    # Setup new egg
    pres = [[['cat', 'dog', 'bat']]]
    rec = [[['dog', 'cat', 'bat']]]
    features = [{'item': 'cat', 'size': 1}, {'item': 'dog', 'size': 2}, {'item': 'bat', 'size': 3}]
    pres_feat = [[features]]
    
    # Needs 3 items to get meaningful weights usually?
    # Or at least 2 for transitions.
    # A->B
    
    egg = quail.Egg(pres=pres_feat, rec=rec)
    
    # Update
    # features arg?
    fp.update(egg)
    # n should increment
    assert fp.n == 2
    # state should change
    assert fp.state is not None

def test_optimal_presenter_init():
    op = quail.OptimalPresenter()
    assert op.strategy == 'random'
    
    params = {'alpha': 5}
    op = quail.OptimalPresenter(params=params)
    assert op.get_params('alpha') == 5

def test_optimal_presenter_order_random():
    op = quail.OptimalPresenter(strategy='random')
    pres = [[['a', 'b', 'c']]]
    rec = [[['a', 'b', 'c']]] # dummy
    egg = quail.Egg(pres=pres, rec=rec)
    
    new_egg = op.order(egg, method='random')
    assert isinstance(new_egg, quail.Egg)
    # Check shuffled? Hard to check randomness deterministically without seed control or stats.
    # Just check dimensions.
    assert new_egg.n_lists == 1

def test_optimal_presenter_order_permute():
    # Needs features
    features = [{'item': 'a', 'val': 1}, {'item': 'b', 'val': 2}, {'item': 'c', 'val': 3}]
    pres = [[['a', 'b', 'c']]]
    rec = [[['a', 'b', 'c']]]
    pres_feat = [[features]]
    # Pass features to egg so it parses them
    egg = quail.Egg(pres=pres_feat, rec=rec)
    
    # Target fingerprint
    # Bias towards clustering?
    # valid_features includes 'val' AND 'temporal' (autogenerated).
    target_fp = [1.0, 0.5] # 2 features
    
    # Pass features to OptimalPresenter so it knows what to optimize
    # Note: OptimalPresenter checks params['fingerprint'].features
    op = quail.OptimalPresenter(strategy='stabilize', features=['val', 'temporal'])
    
    # Use few perms for speed
    # Use euclidean to avoid correlation issues with small/flat vectors
    new_egg = op.order(egg, method='permute', nperms=10, fingerprint=target_fp, distfun='euclidean')
    assert isinstance(new_egg, quail.Egg)

def test_optimal_presenter_order_stick():
    # Use stick method
    features = [{'item': 'a', 'val': 1}, {'item': 'b', 'val': 2}, {'item': 'c', 'val': 3}]
    pres = [[['a', 'b', 'c']]]
    rec = [[['a', 'b', 'c']]]
    pres_feat = [[features]]
    egg = quail.Egg(pres=pres_feat, rec=rec)
    
    op = quail.OptimalPresenter(strategy='stabilize', features=['val'])
    new_egg = op.order(egg, method='stick', fingerprint=[1.0])
    assert isinstance(new_egg, quail.Egg)
