notebooks:

				tools/nb_to_doc.py egg
				tools/nb_to_doc.py basic_analyze_and_plot
				tools/nb_to_doc.py advanced_plotting
				tools/nb_to_doc.py speech_decoding
				tools/nb_to_doc.py fingerprint
